---
- name: VPS preparation
  hosts: vps_servers
  become: true
  roles:
    - vps-prep

- name: Xray installation and configuration
  hosts: 
    - xray_clients
    - vps_servers
  become: true
  roles:
    - xray