---
xray_version: "26.3.27"
xray_user: "nobody"
xray_config_path: "/usr/local/etc/xray"
xray_dat_path: "/usr/local/share/xray"
xray_log_path: "/var/log/xray"
xray_install_geodata: true
xray_service_enabled: true
xray_arch: "64"