---
- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    name: [wget, curl, vim, unzip, ufw]
    state: present

- name: Allow SSH port
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Allow Xray port
  community.general.ufw:
    rule: allow
    port: "{{ xray_port | default(443) }}"
    proto: tcp

- name: Set UFW policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Configure SSH port
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*Port\s+'
    line: "Port {{ ssh_port }}"
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart sshd

- name: Reset SSH connection
  ansible.builtin.meta: reset_connection